services:
  pgdatabase:
    image: postgres:13
    environment:
      - name=value
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
    - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
  ingestor:
    build:
      context: .
      dockerfile: dockerfile
    container_name: ingestor-1
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - pgdatabase
    command: ["tail", "-f", "/dev/null"]

volumes:
  pgdata: